# Site settings
title: PureMachatronics
subtitle: by HTML5 UP
email: info@puremechatronics.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://puremechatronics.com' # the base hostname & protocol for your site
author:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Sass building
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
